### ISSUE TITLE
FEAT: Handle IQ Server Add Application collisions on `Name`

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/sonatype-lifecycle-bulk-scm-onboarder#2]
Certain aspects of an Application in Sonatype IQ must be globally unique in that installation - for example name.

If this situation occurs, the user will see something akin to the below - which is not the most helpful.

```
2024-12-09T14:40:59.165|DEBU|SLI|iq.(*NxiqServer).createAppsInOrg: Created Application SCA Test - db5ec7ef33ba4478b1b0cfc08976740c
 Error when calling `ApplicationsAPI.AddApplication``: 400 Bad Request
 Full HTTP response: &{400 Bad Request 400 HTTP/2.0 2 0 map[Content-Length:[34] Content-Type:[text/plain;charset=utf-8] Date:[Mon, 09 Dec 2024 13:41:02 GMT] Server:[nginx/1.24.0] Set-Cookie:[CLM-CSRF-TOKEN=09b98ecd-273f-4fb2-9615-47d084487125; Path=/; Secure; SameSite=lax] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Content-Type-Options:[nosniff]] {scatest is already used as a name.} 34 [] false false map[] 0xc0007a27e0 0xc00128e160}
```

Example that caused this:
- Application named "SCA Test":
  - Results in App with ID `sca-test` and Name `SCA Test`
- Application named "scatest"
  - Results in App with ID `scatest` and Name `scatest` (collision on Name is reported by IQ Server)

FYI @pkiesslingsonatype

**Comment by pkiesslingsonatype** [comment]
In addition to the above example, if IQ Server has an app called `sca test`, another app called `scatest` cannot be imported as this is seen as a duplicate.
